/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ppe4.Vue;

/**
 *
 * @author ldesirest
 */
public class DetailsPraticien extends javax.swing.JFrame {

    /**
     * Creates new form DetailsPraticien
     */
    public DetailsPraticien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitrePraticien = new javax.swing.JLabel();
        jLabelNomPraticien = new javax.swing.JLabel();
        jLabelPrenomPraticien = new javax.swing.JLabel();
        jLabelAdressePraticien = new javax.swing.JLabel();
        jLabelCodePostalPraticien = new javax.swing.JLabel();
        jLabelVillePraticien = new javax.swing.JLabel();
        jLabelNotorietePraticien = new javax.swing.JLabel();
        jTextFieldNomPraticien = new javax.swing.JTextField();
        jTextFieldPrenomPraticien = new javax.swing.JTextField();
        jTextFieldAdressePraticien = new javax.swing.JTextField();
        jTextFieldCodePostalPraticien = new javax.swing.JTextField();
        jTextFieldVillePraticien = new javax.swing.JTextField();
        jTextFieldNotorietePraticien = new javax.swing.JTextField();
        jButtonQuitPraticien = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitrePraticien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTitrePraticien.setText("Details Praticien");

        jLabelNomPraticien.setText("Nom");

        jLabelPrenomPraticien.setText("Prenom");

        jLabelAdressePraticien.setText("Adresse");

        jLabelCodePostalPraticien.setText("Code Postal");

        jLabelVillePraticien.setText("Ville");

        jLabelNotorietePraticien.setText("Notoriété");

        jTextFieldNomPraticien.setText("jTextField1");

        jTextFieldPrenomPraticien.setText("jTextField2");

        jTextFieldAdressePraticien.setText("jTextField3");

        jTextFieldCodePostalPraticien.setText("jTextField4");

        jTextFieldVillePraticien.setText("jTextField5");

        jTextFieldNotorietePraticien.setText("jTextField6");
        jTextFieldNotorietePraticien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotorietePraticienActionPerformed(evt);
            }
        });

        jButtonQuitPraticien.setText("Quitter");
        jButtonQuitPraticien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitPraticienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTitrePraticien)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonQuitPraticien)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCodePostalPraticien)
                                    .addComponent(jLabelNomPraticien, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPrenomPraticien, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelVillePraticien, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabelAdressePraticien)
                                .addComponent(jLabelNotorietePraticien))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNomPraticien, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addComponent(jTextFieldPrenomPraticien)
                                .addComponent(jTextFieldAdressePraticien)
                                .addComponent(jTextFieldCodePostalPraticien)
                                .addComponent(jTextFieldVillePraticien)
                                .addComponent(jTextFieldNotorietePraticien)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelTitrePraticien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomPraticien)
                    .addComponent(jTextFieldNomPraticien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrenomPraticien)
                    .addComponent(jTextFieldPrenomPraticien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdressePraticien)
                    .addComponent(jTextFieldAdressePraticien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodePostalPraticien)
                    .addComponent(jTextFieldCodePostalPraticien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVillePraticien)
                    .addComponent(jTextFieldVillePraticien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNotorietePraticien)
                    .addComponent(jTextFieldNotorietePraticien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonQuitPraticien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQuitPraticienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitPraticienActionPerformed
    System.exit(0);
    }//GEN-LAST:event_jButtonQuitPraticienActionPerformed

    private void jTextFieldNotorietePraticienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotorietePraticienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotorietePraticienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsPraticien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsPraticien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsPraticien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsPraticien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailsPraticien().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonQuitPraticien;
    private javax.swing.JLabel jLabelAdressePraticien;
    private javax.swing.JLabel jLabelCodePostalPraticien;
    private javax.swing.JLabel jLabelNomPraticien;
    private javax.swing.JLabel jLabelNotorietePraticien;
    private javax.swing.JLabel jLabelPrenomPraticien;
    private javax.swing.JLabel jLabelTitrePraticien;
    private javax.swing.JLabel jLabelVillePraticien;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldAdressePraticien;
    private javax.swing.JTextField jTextFieldCodePostalPraticien;
    private javax.swing.JTextField jTextFieldNomPraticien;
    private javax.swing.JTextField jTextFieldNotorietePraticien;
    private javax.swing.JTextField jTextFieldPrenomPraticien;
    private javax.swing.JTextField jTextFieldVillePraticien;
    // End of variables declaration//GEN-END:variables
}
