/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import controleurs.*;

/**
 *
 * @author btssio
 */
public class VueCompteRendu extends VueAbstraite {

    /**
     * Creates new form VueCompteRendu
     */
    public VueCompteRendu(ControleurAbstrait controleur) {
        super(controleur);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelDateRapport = new javax.swing.JLabel();
        jTextFieldDateRapportRapport = new javax.swing.JTextField();
        jLabelNumeroRapportRapport = new javax.swing.JLabel();
        jTextFieldNumeroRapportRapport = new javax.swing.JTextField();
        jLabelPraticienRapport = new javax.swing.JLabel();
        jLabelOffreRapport = new javax.swing.JLabel();
        jComboBoxMedicamentRapport = new javax.swing.JComboBox();
        jTextFieldMotifVisiteRapport = new javax.swing.JTextField();
        jComboBoxPraticienRapport = new javax.swing.JComboBox();
        jLabelMotifVisiteRapport = new javax.swing.JLabel();
        jButtonDetailsPraticienRapport = new javax.swing.JButton();
        jLabelBilanRapport = new javax.swing.JLabel();
        jTextFieldEchantillonRapport = new javax.swing.JTextField();
        jScrollPaneBilan = new javax.swing.JScrollPane();
        jTextAreaBilanRapport = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelMedicamentRapport = new javax.swing.JLabel();
        jLabelTitreRapport = new javax.swing.JLabel();
        jLabelEchantillonRapport = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jbtnNouveau = new javax.swing.JButton();
        jButtonSuivantVisiteur = new javax.swing.JButton();
        jButtonPrécédentVisiteur = new javax.swing.JButton();
        jButtonQuiRapport = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CompteRendu");

        jLabelDateRapport.setText("Date Rapport");

        jTextFieldDateRapportRapport.setText("jTextField2");

        jLabelNumeroRapportRapport.setText("Numero Rapport");

        jTextFieldNumeroRapportRapport.setText("jTextField1");

        jLabelPraticienRapport.setText("Praticien");

        jLabelOffreRapport.setText("Offre d'échantillon");

        jComboBoxMedicamentRapport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldMotifVisiteRapport.setText("jTextField3");
        jTextFieldMotifVisiteRapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMotifVisiteRapportActionPerformed(evt);
            }
        });

        jComboBoxPraticienRapport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelMotifVisiteRapport.setText("Motif Visite");

        jButtonDetailsPraticienRapport.setText("Détails");

        jLabelBilanRapport.setText("BILAN");

        jTextFieldEchantillonRapport.setText("jTextField4");

        jTextAreaBilanRapport.setColumns(20);
        jTextAreaBilanRapport.setRows(5);
        jScrollPaneBilan.setViewportView(jTextAreaBilanRapport);

        jLabelMedicamentRapport.setText("Médicament");

        jLabelTitreRapport.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabelTitreRapport.setText("Rapport de visite");

        jLabelEchantillonRapport.setText("Nb. Echantillons");

        jbtnNouveau.setText("Nouveau");
        jbtnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNouveauActionPerformed(evt);
            }
        });

        jButtonSuivantVisiteur.setText("Suivant");
        jButtonSuivantVisiteur.setMaximumSize(new java.awt.Dimension(77, 29));
        jButtonSuivantVisiteur.setMinimumSize(new java.awt.Dimension(77, 29));

        jButtonPrécédentVisiteur.setText("Précédent");

        jButtonQuiRapport.setLabel("Retour");
        jButtonQuiRapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuiRapportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonQuiRapport))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jComboBoxPraticienRapport, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDetailsPraticienRapport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelPraticienRapport)
                                                    .addComponent(jLabelDateRapport)
                                                    .addComponent(jLabelMotifVisiteRapport)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(jLabelBilanRapport)))
                                        .addGap(39, 39, 39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelNumeroRapportRapport)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMotifVisiteRapport)
                                    .addComponent(jTextFieldDateRapportRapport)
                                    .addComponent(jTextFieldNumeroRapportRapport)
                                    .addComponent(jScrollPaneBilan, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jButtonPrécédentVisiteur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSuivantVisiteur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnNouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabelOffreRapport)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxMedicamentRapport, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelMedicamentRapport)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEchantillonRapport)
                                    .addComponent(jTextFieldEchantillonRapport, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator2))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTitreRapport)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreRapport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumeroRapportRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumeroRapportRapport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPraticienRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPraticienRapport)
                    .addComponent(jButtonDetailsPraticienRapport))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDateRapportRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDateRapport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMotifVisiteRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMotifVisiteRapport))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBilanRapport)
                    .addComponent(jScrollPaneBilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPrécédentVisiteur)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnNouveau)
                        .addComponent(jButtonSuivantVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMedicamentRapport)
                    .addComponent(jLabelEchantillonRapport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMedicamentRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEchantillonRapport)
                    .addComponent(jLabelOffreRapport, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jButtonQuiRapport)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMotifVisiteRapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMotifVisiteRapportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMotifVisiteRapportActionPerformed

    private void jbtnNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNouveauActionPerformed
        controleur.retourner();
    }//GEN-LAST:event_jbtnNouveauActionPerformed

    private void jButtonQuiRapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuiRapportActionPerformed
    controleur.retourner();        
    }//GEN-LAST:event_jButtonQuiRapportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueCompteRendu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueCompteRendu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueCompteRendu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueCompteRendu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new VueCompteRendu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDetailsPraticienRapport;
    private javax.swing.JButton jButtonPrécédentVisiteur;
    private javax.swing.JButton jButtonQuiRapport;
    private javax.swing.JButton jButtonSuivantVisiteur;
    private javax.swing.JComboBox jComboBoxMedicamentRapport;
    private javax.swing.JComboBox jComboBoxPraticienRapport;
    private javax.swing.JLabel jLabelBilanRapport;
    private javax.swing.JLabel jLabelDateRapport;
    private javax.swing.JLabel jLabelEchantillonRapport;
    private javax.swing.JLabel jLabelMedicamentRapport;
    private javax.swing.JLabel jLabelMotifVisiteRapport;
    private javax.swing.JLabel jLabelNumeroRapportRapport;
    private javax.swing.JLabel jLabelOffreRapport;
    private javax.swing.JLabel jLabelPraticienRapport;
    private javax.swing.JLabel jLabelTitreRapport;
    private javax.swing.JScrollPane jScrollPaneBilan;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextAreaBilanRapport;
    private javax.swing.JTextField jTextFieldDateRapportRapport;
    private javax.swing.JTextField jTextFieldEchantillonRapport;
    private javax.swing.JTextField jTextFieldMotifVisiteRapport;
    private javax.swing.JTextField jTextFieldNumeroRapportRapport;
    private javax.swing.JButton jbtnNouveau;
    // End of variables declaration//GEN-END:variables
}
