/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import controleurs.ControleurAbstrait;
import controleurs.CtrlCompteRendu;

/**
 *
 * @author btssio
 */
public class VueCompteRendu extends VueAbstraite {

    /**
     * Creates new form VueCompteRendu
     */
    public VueCompteRendu(ControleurAbstrait controleur) {
        super(controleur);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnRetour = new javax.swing.JButton();
        jLabelDateRapportRapport = new javax.swing.JLabel();
        jTextFieldDateRapportRapport = new javax.swing.JTextField();
        jLabelNumeroRapportRapport = new javax.swing.JLabel();
        jTextFieldNumeroRapportRapport = new javax.swing.JTextField();
        jLabelPraticienRapport = new javax.swing.JLabel();
        jLabelOffreRapport = new javax.swing.JLabel();
        jComboBoxMedicamentRapport = new javax.swing.JComboBox();
        jTextFieldMotifVisiteRapport = new javax.swing.JTextField();
        jComboBoxPraticienRapport = new javax.swing.JComboBox();
        jLabelMotifVisiteRapport = new javax.swing.JLabel();
        jButtonDetailsPraticienRapport = new javax.swing.JButton();
        jLabelBilanRapport = new javax.swing.JLabel();
        jTextFieldEchantillonRapport = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaBilanRapport = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelMedicamentRapport = new javax.swing.JLabel();
        jLabelTitreRapport = new javax.swing.JLabel();
        jLabelEchantillonRapport = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CompteRendu");

        jbtnRetour.setText("Retour");
        jbtnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRetourActionPerformed(evt);
            }
        });

        jLabelDateRapportRapport.setText("Date Rapport");

        jTextFieldDateRapportRapport.setText("jTextField2");

        jLabelNumeroRapportRapport.setText("Numero Rapport");

        jTextFieldNumeroRapportRapport.setText("jTextField1");

        jLabelPraticienRapport.setText("Praticien");

        jLabelOffreRapport.setText("Offre d'échantillon");

        jComboBoxMedicamentRapport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldMotifVisiteRapport.setText("jTextField3");
        jTextFieldMotifVisiteRapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMotifVisiteRapportActionPerformed(evt);
            }
        });

        jComboBoxPraticienRapport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelMotifVisiteRapport.setText("Motif Visite");

        jButtonDetailsPraticienRapport.setText("Détails");

        jLabelBilanRapport.setText("BILAN");

        jTextFieldEchantillonRapport.setText("jTextField4");

        jTextAreaBilanRapport.setColumns(20);
        jTextAreaBilanRapport.setRows(5);
        jScrollPane1.setViewportView(jTextAreaBilanRapport);

        jLabelMedicamentRapport.setText("Médicament");

        jLabelTitreRapport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTitreRapport.setText("Rapport de visite");

        jLabelEchantillonRapport.setText("Nb. Echantillons");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnRetour))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addComponent(jLabelTitreRapport))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelNumeroRapportRapport)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabelBilanRapport))
                                .addComponent(jLabelPraticienRapport)
                                .addComponent(jLabelDateRapportRapport)
                                .addComponent(jLabelMotifVisiteRapport))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jComboBoxPraticienRapport, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonDetailsPraticienRapport))
                                        .addComponent(jTextFieldNumeroRapportRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldDateRapportRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldMotifVisiteRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelOffreRapport)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jComboBoxMedicamentRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEchantillonRapport))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelMedicamentRapport)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEchantillonRapport)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelTitreRapport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumeroRapportRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumeroRapportRapport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDetailsPraticienRapport)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPraticienRapport)
                        .addComponent(jComboBoxPraticienRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabelDateRapportRapport))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDateRapportRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMotifVisiteRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMotifVisiteRapport))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabelBilanRapport))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMedicamentRapport)
                    .addComponent(jLabelEchantillonRapport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldEchantillonRapport, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxMedicamentRapport, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelOffreRapport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jbtnRetour)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRetourActionPerformed
        controleur.retourner();// TODO add your handling code here:
    }//GEN-LAST:event_jbtnRetourActionPerformed

    private void jTextFieldMotifVisiteRapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMotifVisiteRapportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMotifVisiteRapportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueCompteRendu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueCompteRendu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueCompteRendu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueCompteRendu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new VueCompteRendu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetailsPraticienRapport;
    private javax.swing.JComboBox jComboBoxMedicamentRapport;
    private javax.swing.JComboBox jComboBoxPraticienRapport;
    private javax.swing.JLabel jLabelBilanRapport;
    private javax.swing.JLabel jLabelDateRapportRapport;
    private javax.swing.JLabel jLabelEchantillonRapport;
    private javax.swing.JLabel jLabelMedicamentRapport;
    private javax.swing.JLabel jLabelMotifVisiteRapport;
    private javax.swing.JLabel jLabelNumeroRapportRapport;
    private javax.swing.JLabel jLabelOffreRapport;
    private javax.swing.JLabel jLabelPraticienRapport;
    private javax.swing.JLabel jLabelTitreRapport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextAreaBilanRapport;
    private javax.swing.JTextField jTextFieldDateRapportRapport;
    private javax.swing.JTextField jTextFieldEchantillonRapport;
    private javax.swing.JTextField jTextFieldMotifVisiteRapport;
    private javax.swing.JTextField jTextFieldNumeroRapportRapport;
    private javax.swing.JButton jbtnRetour;
    // End of variables declaration//GEN-END:variables
}
