/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import controleurs.ControleurAbstrait;

/**
 *
 * @author btssio
 */
public class VueVisiteur extends VueAbstraite {

    /**
     * Creates new form VueMenu
     */
    public VueVisiteur(ControleurAbstrait controleur) {
        super(controleur);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnRetournerMenu = new javax.swing.JButton();
        jComboBoxPrenomVisiteur = new javax.swing.JComboBox();
        jLabelVilleVisiteur = new javax.swing.JLabel();
        jComboBoxNomVisiteur = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldAdresseVisiteur = new javax.swing.JTextField();
        jLabelNomVisiteur = new javax.swing.JLabel();
        jLabelPrenomVisiteur = new javax.swing.JLabel();
        jLabelAdresseVisiteur = new javax.swing.JLabel();
        jLabelCodePostalVisiteur = new javax.swing.JLabel();
        jLabelTitreVisiteur = new javax.swing.JLabel();
        jTextFieldCodePostalVisiteur = new javax.swing.JTextField();
        jTextFieldVilleVisiteur = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visiteur");

        jbtnRetournerMenu.setText("Retour");
        jbtnRetournerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRetournerMenuActionPerformed(evt);
            }
        });

        jComboBoxPrenomVisiteur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelVilleVisiteur.setText("Ville");

        jComboBoxNomVisiteur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxNomVisiteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNomVisiteurActionPerformed(evt);
            }
        });

        jTextFieldAdresseVisiteur.setText("jTextField3");

        jLabelNomVisiteur.setText("Nom");

        jLabelPrenomVisiteur.setText("Prenom");

        jLabelAdresseVisiteur.setText("Adresse");

        jLabelCodePostalVisiteur.setText("Code Postal");

        jLabelTitreVisiteur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitreVisiteur.setText("Details Visiteur");

        jTextFieldCodePostalVisiteur.setText("jTextField4");

        jTextFieldVilleVisiteur.setText("jTextField5");
        jTextFieldVilleVisiteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVilleVisiteurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnRetournerMenu)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabelTitreVisiteur))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCodePostalVisiteur)
                                .addComponent(jLabelNomVisiteur, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelPrenomVisiteur, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelVilleVisiteur, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabelAdresseVisiteur))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldVilleVisiteur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jTextFieldCodePostalVisiteur, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAdresseVisiteur, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxPrenomVisiteur, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxNomVisiteur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitreVisiteur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomVisiteur)
                    .addComponent(jComboBoxNomVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrenomVisiteur)
                    .addComponent(jComboBoxPrenomVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdresseVisiteur)
                    .addComponent(jTextFieldAdresseVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodePostalVisiteur)
                    .addComponent(jTextFieldCodePostalVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVilleVisiteur)
                    .addComponent(jTextFieldVilleVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jbtnRetournerMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRetournerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRetournerMenuActionPerformed
         controleur.retourner();
    }//GEN-LAST:event_jbtnRetournerMenuActionPerformed

    private void jComboBoxNomVisiteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNomVisiteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNomVisiteurActionPerformed

    private void jTextFieldVilleVisiteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVilleVisiteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVilleVisiteurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueVisiteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueVisiteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueVisiteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueVisiteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new VueMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxNomVisiteur;
    private javax.swing.JComboBox jComboBoxPrenomVisiteur;
    private javax.swing.JLabel jLabelAdresseVisiteur;
    private javax.swing.JLabel jLabelCodePostalVisiteur;
    private javax.swing.JLabel jLabelNomVisiteur;
    private javax.swing.JLabel jLabelPrenomVisiteur;
    private javax.swing.JLabel jLabelTitreVisiteur;
    private javax.swing.JLabel jLabelVilleVisiteur;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldAdresseVisiteur;
    private javax.swing.JTextField jTextFieldCodePostalVisiteur;
    private javax.swing.JTextField jTextFieldVilleVisiteur;
    private javax.swing.JButton jbtnRetournerMenu;
    // End of variables declaration//GEN-END:variables
}
