/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import controleurs.*;

/**
 *
 * @author btssio
 */
public class VueVisiteur extends VueAbstraite {

    /**
     * Creates new form VueMenu
     */
    public VueVisiteur(ControleurAbstrait controleur) {
        super(controleur);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnQuitVisiteur = new javax.swing.JButton();
        jLabelLaboVisiteur = new javax.swing.JLabel();
        jSeparatorVisiteur = new javax.swing.JSeparator();
        jTextFieldCodePostale = new javax.swing.JTextField();
        jLabelNomVisiteur = new javax.swing.JLabel();
        jLabelPrenomVisiteur = new javax.swing.JLabel();
        jLabelCodeSecteurVisiteur = new javax.swing.JLabel();
        jLabelTitreVisiteur = new javax.swing.JLabel();
        jLabelChercherVisiteur = new javax.swing.JLabel();
        jComboBoxChercherVisiteur = new javax.swing.JComboBox();
        jButtonOkVisiteur = new javax.swing.JButton();
        jTextFieldNomVisiteur = new javax.swing.JTextField();
        jTextFieldPrénomVisiteur = new javax.swing.JTextField();
        jLabelVilleVisiteur = new javax.swing.JLabel();
        jComboBoxSecteurVisiteur = new javax.swing.JComboBox();
        jComboBoxLaboVisiteur = new javax.swing.JComboBox();
        jTextFieldVilleVisiteur = new javax.swing.JTextField();
        jButtonPrécédentVisiteur = new javax.swing.JButton();
        jButtonSuivantVisiteur = new javax.swing.JButton();

        setTitle("Visiteur");
        setName("frameVisiteur"); // NOI18N

        jbtnQuitVisiteur.setText("Retour");
        jbtnQuitVisiteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQuitVisiteurActionPerformed(evt);
            }
        });

        jLabelLaboVisiteur.setText("Labo");

        jTextFieldCodePostale.setText("jTextField3");

        jLabelNomVisiteur.setText("Nom");

        jLabelPrenomVisiteur.setText("Prenom");

        jLabelCodeSecteurVisiteur.setText("Secteur");

        jLabelTitreVisiteur.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabelTitreVisiteur.setText("Visiteur");

        jLabelChercherVisiteur.setText("Chercher");

        jComboBoxChercherVisiteur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonOkVisiteur.setText("Ok");

        jTextFieldNomVisiteur.setText("jTextField1");

        jTextFieldPrénomVisiteur.setText("jTextField2");

        jLabelVilleVisiteur.setText("Ville");

        jComboBoxSecteurVisiteur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxLaboVisiteur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldVilleVisiteur.setText("jTextField3");

        jButtonPrécédentVisiteur.setText("Précédent");

        jButtonSuivantVisiteur.setText("Suivant");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabelTitreVisiteur)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomVisiteur)
                            .addComponent(jLabelPrenomVisiteur)
                            .addComponent(jLabelVilleVisiteur)
                            .addComponent(jLabelCodeSecteurVisiteur)
                            .addComponent(jLabelLaboVisiteur))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNomVisiteur)
                            .addComponent(jTextFieldPrénomVisiteur, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSecteurVisiteur, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxLaboVisiteur, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextFieldCodePostale, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldVilleVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelChercherVisiteur)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxChercherVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOkVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparatorVisiteur)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButtonPrécédentVisiteur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSuivantVisiteur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnQuitVisiteur)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreVisiteur)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelChercherVisiteur)
                    .addComponent(jComboBoxChercherVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOkVisiteur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparatorVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomVisiteur)
                    .addComponent(jTextFieldNomVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrenomVisiteur)
                    .addComponent(jTextFieldPrénomVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodePostale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVilleVisiteur)
                    .addComponent(jTextFieldVilleVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodeSecteurVisiteur)
                    .addComponent(jComboBoxSecteurVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLaboVisiteur)
                    .addComponent(jComboBoxLaboVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnQuitVisiteur)
                    .addComponent(jButtonSuivantVisiteur)
                    .addComponent(jButtonPrécédentVisiteur))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnQuitVisiteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQuitVisiteurActionPerformed
        controleur.retourner();
    }//GEN-LAST:event_jbtnQuitVisiteurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueVisiteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueVisiteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueVisiteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueVisiteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new VueMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOkVisiteur;
    private javax.swing.JButton jButtonPrécédentVisiteur;
    private javax.swing.JButton jButtonSuivantVisiteur;
    private javax.swing.JComboBox jComboBoxChercherVisiteur;
    private javax.swing.JComboBox jComboBoxLaboVisiteur;
    private javax.swing.JComboBox jComboBoxSecteurVisiteur;
    private javax.swing.JLabel jLabelChercherVisiteur;
    private javax.swing.JLabel jLabelCodeSecteurVisiteur;
    private javax.swing.JLabel jLabelLaboVisiteur;
    private javax.swing.JLabel jLabelNomVisiteur;
    private javax.swing.JLabel jLabelPrenomVisiteur;
    private javax.swing.JLabel jLabelTitreVisiteur;
    private javax.swing.JLabel jLabelVilleVisiteur;
    private javax.swing.JSeparator jSeparatorVisiteur;
    private javax.swing.JTextField jTextFieldCodePostale;
    private javax.swing.JTextField jTextFieldNomVisiteur;
    private javax.swing.JTextField jTextFieldPrénomVisiteur;
    private javax.swing.JTextField jTextFieldVilleVisiteur;
    private javax.swing.JButton jbtnQuitVisiteur;
    // End of variables declaration//GEN-END:variables
}
